name: al_cli_app
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  meta: ^1.8.0
  http: ^0.13.4
  dio: ^4.0.6
  english_words: ^4.0.0


  
